Repository wordpress-mobile/WordPress-Utils-Android, pull requests merged in 2022-11, with the labels that each got.

#111 Update `minSdkVersion` (from `21` to `24`)
  WordPressUtils/build.gradle
  build.gradle
  settings.gradle
Labels: enhancement, Tooling

#113 Update Kotlin to 1.6.10
  WordPressUtils/build.gradle
  WordPressUtils/src/test/java/org/wordpress/android/util/LogFileCleanerTest.kt
  WordPressUtils/src/test/java/org/wordpress/android/util/LogFileHelpersTest.kt
  WordPressUtils/src/test/java/org/wordpress/android/util/LogFileWriterTest.kt
  build.gradle
  settings.gradle
Labels: enhancement, Tooling

#114 Update Apache Commons Text to 1.10.0
  build.gradle
Labels: enhancement, Tooling

#115 [Build] Remove Fetch Style Plugin
  build.gradle
  settings.gradle
Labels: Tooling, Tech Debt

#116 Use Android AMI in Buildkite
  .buildkite/pipeline.yml
Labels: Tooling
